// 서버에서 정의한 에러 코드
// 참고용

const responseCodes = {
  RESPONSE_CODE_OK : 200,
  RESPONSE_CODE_NOT_MODIFIED : 304,
  RESPONSE_BAD_REQUEST : 400,
  RESPONSE_CODE_UNAUTHORIZED : 401,
  RESPONSE_CODE_FORBIDDEN : 403,
  RESPONSE_CODE_NOT_FOUND : 404,
  RESPONSE_CODE_INTERNAL_SERVER_ERROR : 500
};

const errorCodes = {
  // 18xx 번대 : 자주 일어나는 특수 코드
  ERROR_CODE_INVALID_USER_ID_OR_PASSWORD : 1818,
  ERROR_CODE_INVALID_PARAMETERS : 1828,
  ERROR_CODE_INTERNAL_SERVER_ERROR : 1838,
  ERROR_CODE_DATA_NOT_FOUND : 1839,
  ERROR_CODE_VERSION_CHECK_FAILED : 1840,
  // 2000 번대 : 인증 및 권한 관련
  ERROR_CODE_INVALID_SECURITY_TOKEN : 2000,
  ERROR_CODE_DIFFERENCE_USER_ID_AND_SECURITY_TOKEN  : 2001,
  ERROR_CODE_FORBIDDEN : 2002,
  ERROR_CODE_FORBIDDEN_POLICY_NOT_AGREE : 2003,
  ERROR_CODE_EXPIRED : 2004,
  ERROR_CODE_MAIL_LINK_EXPIRED : 2005,
  ERROR_CODE_USER_RESTRICTED : 2006,

  // 3000 번대 : 유저 관련
  ERROR_CODE_USER_NOT_FOUND : 3000,
  ERROR_CODE_CREATOR_CHANNEL_NOT_FOUND : 3001,
  ERROR_CODE_CREATOR_CHANNEL_NO_VIDEO : 3002,
  ERROR_CODE_CREATOR_NOT_ENOUGH_SUBSCRIBERS : 3003,
  ERROR_CODE_CREATOR_CHANNEL_ALREADY_SIGNUP : 3004,
  ERROR_CODE_CREATOR_NOT_MATCH_CHANNEL_BEFORE : 3005,
  ERROR_CODE_USER_NOT_EXISTS : 3006,
  ERROR_CODE_USERNAME_ALREADY_EXISTS : 3007,
  ERROR_CODE_EMAIL_ALREADY_EXISTS : 3008,

  // 4000 번대 : 일반
  ERROR_DUPLICATE_NAME : 4000,
  ERROR_DUPLICATE_DATA : 4001,
  ERROR_BAD_REQUEST : 4002,
};

export {
  responseCodes,
  errorCodes,
}