import {
  MainCategory as Main,
  SubCategoryInWeapon as Weapon,
  SubCategoryInSubWeapon as SubWeapon,
  SubCategoryInSkill as Skill,
  SubCategoryInSpell as Spell,
  SubCategoryInSpiritAshes as Spirit,
  SubCategoryInNpc as Npc,
  SubCategoryIngGeneralItem as Item,
} from './define';

const weaponDb = {
  [1]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '대거' },
  [2]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '패링 대거' },
  [3]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '자비의 단검' },
  [4]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '대형 나이프' },
  [5]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '피투성이 단도' },
  [6]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '황동 단도' },
  [7]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '협차' },
  [8]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '축제의 손낫' },
  [9]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '상아 손낫' },
  [10]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '결정 나이프' },
  [11]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '전갈의 침' },
  [12]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '친퀘디아' },
  [13]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '휘석 크리스' },
  [14]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '레두비아' },
  [15]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '사명의 칼날' },
  [16]: { mainCategory: Main.weapon, subCategory: Weapon.dagger, name: '검은 칼날' },

  [21]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '숏 소드' },
  [22]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '롱 소드' },
  [23]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '브로드 소드' },
  [24]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '낡은 직검' },
  [25]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '군주군의 직검' },
  [26]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '귀인의 세검' },
  [27]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '지팡이검' },
  [28]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '전쟁매의 발톱검' },
  [29]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '라줄리의 휘석검' },
  [30]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '카리아의 휘석검' },
  [31]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '결정검' },
  [32]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '부패한 결정검' },
  [33]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '미켈라의 기사검' },
  [34]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '의장 직검' },
  [35]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '황금 묘비' },
  [36]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '트리나의 검' },
  [37]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '에오히드의 보검' },
  [38]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '비문자 검' },
  [39]: { mainCategory: Main.weapon, subCategory: Weapon.straightSword, name: '밤과 불꽃의 검' },

  [41]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '바스타드 소드' },
  [42]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '클레이모어' },
  [43]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '철 대검' },
  [44]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '군주군의 대검' },
  [45]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '기사 대검' },
  [46]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '땅 잃은 기사의 대검' },
  [47]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '두갈래 대검' },
  [48]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '플랑베르주' },
  [49]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '가고일의 대검' },
  [50]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '가고일의 흑검' },
  [51]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '나뉘지 않는 쌍생아의 검' },
  [52]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '미에로스의 검' },
  [53]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '마레 가의 집행검' },
  [54]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '오르도비스의 대검' },
  [55]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '백왕의 검' },
  [56]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '죽음부지깽이' },
  [57]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '헬펜의 첨탑' },
  [58]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '모독의 성검' },
  [59]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '황금률의 대검' },
  [60]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '암월의 대검' },
  [61]: { mainCategory: Main.weapon, subCategory: Weapon.greatSword, name: '신이 남긴 검' },

  [71]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '츠바이헨더' },
  [72]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '그레이트 소드' },
  [73]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '파수견의 대검' },
  [74]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '트롤의 황금검' },
  [75]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '거인의 마법검' },
  [76]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '왕가의 그레이트 소드' },
  [77]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '검 잇기의 대검' },
  [78]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '유적의 대검' },
  [79]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '별 부수는 대검' },
  [80]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '신 사냥의 검' },
  [81]: { mainCategory: Main.weapon, subCategory: Weapon.colossalSword, name: '말리케스의 흑검' },

  [91]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '레이피어' },
  [92]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '에스톡' },
  [93]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '귀인의 에스톡' },
  [94]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '귀부기사의 검' },
  [95]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '로지에르의 자검' },
  [96]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '개미가시 레이피어' },
  [97]: { mainCategory: Main.weapon, subCategory: Weapon.thrustingSword, name: '빙결의 침' },

  [101]: { mainCategory: Main.weapon, subCategory: Weapon.heavyThrustingSword, name: '그레이트 에페' },
  [102]: { mainCategory: Main.weapon, subCategory: Weapon.heavyThrustingSword, name: '신의 살갗 대자검' },
  [103]: { mainCategory: Main.weapon, subCategory: Weapon.heavyThrustingSword, name: '피의 헬리케' },
  [104]: { mainCategory: Main.weapon, subCategory: Weapon.heavyThrustingSword, name: '용왕의 바위검' },

  [111]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '시미터' },
  [112]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '펄션' },
  [113]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '샴시르' },
  [114]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '그로스메서' },
  [115]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '산적의 곡도' },
  [116]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '쇼텔' },
  [117]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '시체 뒤지는 자의 곡검' },
  [118]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '당랑도' },
  [119]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '수인의 곡도' },
  [120]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '유수의 곡검' },
  [121]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '뱀신의 곡도' },
  [122]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '용암도' },
  [123]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '녹스의 유체검' },
  [124]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '아스테르의 날개' },
  [125]: { mainCategory: Main.weapon, subCategory: Weapon.curvedSword, name: '일식의 쇼텔' },

  [131]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '참마도' },
  [132]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '흉조의 아이 대도' },
  [133]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '승병의 화염도' },
  [134]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '수인의 대곡도' },
  [135]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '사냥개의 긴 이빨' },
  [136]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '흑왕의 대검' },
  [137]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '자미엘의 곡검' },
  [138]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '토룡의 비늘검' },
  [139]: { mainCategory: Main.weapon, subCategory: Weapon.curvedGreatSword, name: '모르고트의 저주검' },

  [141]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '타도' },
  [142]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '긴 이빨' },
  [143]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '뱀 뼈의 도' },
  [144]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '운철도' },
  [145]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '명도 월은' },
  [146]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '시산혈하' },
  [147]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '용비늘도' },
  [148]: { mainCategory: Main.weapon, subCategory: Weapon.katana, name: '말레니아의 의수도' },

  [151]: { mainCategory: Main.weapon, subCategory: Weapon.twinBlade, name: '트윈 블레이드' },
  [152]: { mainCategory: Main.weapon, subCategory: Weapon.twinBlade, name: '트윈 나이트소드' },
  [153]: { mainCategory: Main.weapon, subCategory: Weapon.twinBlade, name: '신의 살갗 쌍날검' },
  [154]: { mainCategory: Main.weapon, subCategory: Weapon.twinBlade, name: '가고일의 쌍날검' },
  [155]: { mainCategory: Main.weapon, subCategory: Weapon.twinBlade, name: '가고일의 흑쌍날검' },
  [156]: { mainCategory: Main.weapon, subCategory: Weapon.twinBlade, name: '엘레오노라의 쌍치도' },

  [161]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '핸드 액스' },
  [162]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '두갈래 손도끼' },
  [163]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '배틀 액스' },
  [164]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '일그러진 도끼' },
  [165]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '치열 도끼' },
  [166]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '철 나대' },
  [167]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '하이랜드 액스' },
  [168]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '축제의 나대' },
  [169]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '산 제물 도끼' },
  [170]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '빙각의 도끼' },
  [171]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '파문의 검' },
  [172]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '폭풍 매 도끼' },
  [173]: { mainCategory: Main.weapon, subCategory: Weapon.axe, name: '로제스의 도끼' },

  [181]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '그레이트 액스' },
  [182]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '초승달도끼' },
  [183]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '긴 자루 나대' },
  [184]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '요참의 큰 나대' },
  [185]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '흉조잡이의 큰 나대' },
  [186]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '녹슨 닻' },
  [187]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '해체 식칼' },
  [188]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '가고일의 대형 도끼' },
  [189]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '가고일의 흑도끼' },
  [190]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '날개의 큰 뿔' },
  [191]: { mainCategory: Main.weapon, subCategory: Weapon.greatAxe, name: '고드릭의 왕 도끼' },

  [201]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '곤봉' },
  [202]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '굽은 곤봉' },
  [203]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '이빨 달린 곤봉' },
  [204]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '돌 곤봉' },
  [205]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '메이스' },
  [206]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '모닝스타' },
  [207]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '워 피크' },
  [208]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '해머' },
  [209]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '승병의 화염망치' },
  [210]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '바레의 꽃다발' },
  [211]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '사자들의 피리' },
  [212]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '녹스의 유체망치' },
  [213]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '반지손가락' },
  [214]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '온 지혜의 왕홀' },
  [215]: { mainCategory: Main.weapon, subCategory: Weapon.hammer, name: '마리카의 망치' },

  [221]: { mainCategory: Main.weapon, subCategory: Weapon.flail, name: '철퇴' },
  [222]: { mainCategory: Main.weapon, subCategory: Weapon.flail, name: '밤 기병의 철퇴' },
  [223]: { mainCategory: Main.weapon, subCategory: Weapon.flail, name: '편곤' },
  [224]: { mainCategory: Main.weapon, subCategory: Weapon.flail, name: '가족의 머리' },
  [225]: { mainCategory: Main.weapon, subCategory: Weapon.flail, name: '떨어진 별들' },

  [231]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '라지 클럽' },
  [232]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '큰 굽은 곤봉' },
  [233]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '그레이트 메이스' },
  [234]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '곡괭이' },
  [235]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '적석 망치' },
  [236]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '배틀 해머' },
  [237]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '부패한 배틀 해머' },
  [238]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '축제의 큰 두개' },
  [239]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '그레이트스타즈' },
  [240]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '큰 뿔 망치' },
  [241]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '사자들의 긴 피리' },
  [242]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '존안의 촛대' },
  [243]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '짐승 발톱 대형 망치' },
  [244]: { mainCategory: Main.weapon, subCategory: Weapon.greatHammer, name: '세계 먹는 자의 왕홀' },

  [251]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '투사의 대형 도끼' },
  [252]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '부패한 대형 도끼' },
  [253]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '골렘의 도끼창' },
  [254]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '거인 부수기' },
  [255]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '주교의 대형 화염 망치' },
  [256]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '그레이트 클럽' },
  [257]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '트롤 해머' },
  [258]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '대룡조' },
  [259]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '파수견의 석장' },
  [260]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '화신의 석장' },
  [261]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '부패한 석장' },
  [262]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '사자들의 부채피리' },
  [263]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '기자의 수레바퀴' },
  [264]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '성수의 턱' },
  [265]: { mainCategory: Main.weapon, subCategory: Weapon.colossalWeapon, name: '고드프리의 왕 도끼' },

  [271]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '숏 스피어' },
  [272]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '철 창' },
  [273]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '스피어' },
  [274]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '파르티잔' },
  [275]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '파이크' },
  [276]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '가시몽둥이' },
  [277]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '십문자치도' },
  [278]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '진흙 인간의 작살' },
  [279]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '축제 늑골 쇠스랑' },
  [280]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '막대기 토치' },
  [281]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '책문 촛대' },
  [282]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '결정창' },
  [283]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '부패한 결정창' },
  [284]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '귀부기사의 창' },
  [285]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '죽음 의례의 창' },
  [286]: { mainCategory: Main.weapon, subCategory: Weapon.spear, name: '그랑삭스의 벼락' },

  [291]: { mainCategory: Main.weapon, subCategory: Weapon.greatSpear, name: '랜스' },
  [292]: { mainCategory: Main.weapon, subCategory: Weapon.greatSpear, name: '트리 스피어' },
  [293]: { mainCategory: Main.weapon, subCategory: Weapon.greatSpear, name: '큰 뱀 사냥꾼' },
  [294]: { mainCategory: Main.weapon, subCategory: Weapon.greatSpear, name: '실루리아의 나무 창' },
  [295]: { mainCategory: Main.weapon, subCategory: Weapon.greatSpear, name: '바이크의 전투 창' },
  [296]: { mainCategory: Main.weapon, subCategory: Weapon.greatSpear, name: '모그윈의 성창' },

  [301]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '할버드' },
  [302]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '땅 잃은 기사의 도끼창' },
  [303]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '루체른' },
  [304]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '글레이브' },
  [305]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '천한 병사의 쇼텔' },
  [306]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '천한 병사의 톱' },
  [307]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '수호자의 검창' },
  [308]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '가고일의 도끼창' },
  [309]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '가고일의 흑도끼창' },
  [310]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '밤 기병의 글레이브' },
  [311]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '벌레의 글레이브' },
  [312]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '일그러진 파문 도끼창' },
  [313]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '황금 할버드' },
  [314]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '용 할버드' },
  [315]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '로레타의 전투 낫' },
  [316]: { mainCategory: Main.weapon, subCategory: Weapon.halberd, name: '노장의 군기' },

  [321]: { mainCategory: Main.weapon, subCategory: Weapon.reaper, name: '대낫' },
  [322]: { mainCategory: Main.weapon, subCategory: Weapon.reaper, name: '묘지의 대낫' },
  [323]: { mainCategory: Main.weapon, subCategory: Weapon.reaper, name: '광륜의 대낫' },
  [324]: { mainCategory: Main.weapon, subCategory: Weapon.reaper, name: '날개낫' },

  [331]: { mainCategory: Main.weapon, subCategory: Weapon.whip, name: '채찍' },
  [332]: { mainCategory: Main.weapon, subCategory: Weapon.whip, name: '가시 채찍' },
  [333]: { mainCategory: Main.weapon, subCategory: Weapon.whip, name: '우루미' },
  [334]: { mainCategory: Main.weapon, subCategory: Weapon.whip, name: '호슬로의 꽃잎' },
  [335]: { mainCategory: Main.weapon, subCategory: Weapon.whip, name: '용암 채찍의 촛대' },
  [336]: { mainCategory: Main.weapon, subCategory: Weapon.whip, name: '거인의 적발' },

  [341]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '세스타스' },
  [342]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '스파이크 세스타스' },
  [343]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '카타르' },
  [344]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '철구권' },
  [345]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '가시 철구권' },
  [346]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '매달리는 손뼈' },
  [347]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '노장의 의족' },
  [348]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '비문자의 파타' },
  [349]: { mainCategory: Main.weapon, subCategory: Weapon.fist, name: '접목된 비룡' },

  [351]: { mainCategory: Main.weapon, subCategory: Weapon.claw, name: '갈고리 발톱' },
  [352]: { mainCategory: Main.weapon, subCategory: Weapon.claw, name: '사냥개의 발톱' },
  [353]: { mainCategory: Main.weapon, subCategory: Weapon.claw, name: '독사의 이빨' },
  [354]: { mainCategory: Main.weapon, subCategory: Weapon.claw, name: '맹금의 발톱' },
}

const subWeaponDb = {
  [361]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '별점 지팡이' },
  [362]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '휘석 지팡이' },
  [363]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '학원의 휘석 지팡이' },
  [364]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '채석 지팡이' },
  [365]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '아인 여왕의 지팡이' },
  [366]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '아줄의 휘석 지팡이' },
  [367]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '루사트의 휘석 지팡이' },
  [368]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '카리아의 휘석 지팡이' },
  [369]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '카리아의 휘검 지팡이' },
  [370]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '카리아의 왕홀' },
  [371]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '백금 지팡이' },
  [372]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '상실의 지팡이' },
  [373]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '미어의 휘석 지팡이' },
  [374]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '결정 지팡이' },
  [375]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '부패한 결정 지팡이' },
  [376]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '운석 지팡이' },
  [377]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '죄인의 지팡이' },
  [378]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.staff, name: '죽음의 왕자의 지팡이' },

  [381]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '손가락의 성인' },
  [382]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '황금 나무의 성인' },
  [383]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '황금률의 성인' },
  [384]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '조약돌의 성인' },
  [385]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '거인의 성인' },
  [386]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '신 사냥의 성인' },
  [387]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '발톱 자국의 성인' },
  [388]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '미친 불의 성인' },
  [389]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.sacredSeal, name: '용찬의 표식' },

  [391]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.lightBow, name: '숏 보우' },
  [392]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.lightBow, name: '컴포지트 보우' },
  [393]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.lightBow, name: '붉은 나무 숏 보우' },
  [394]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.lightBow, name: '혼종의 숏 보우' },
  [395]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.lightBow, name: '하프 보우' },

  [401]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '롱보우' },
  [402]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '백금의 활' },
  [403]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '검은 활' },
  [404]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '도르래 활' },
  [405]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '뿔 활' },
  [406]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '뱀 활' },
  [407]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.bow, name: '황금 나무의 활' },

  [411]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatBow, name: '대궁' },
  [412]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatBow, name: '골렘의 대궁' },
  [413]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatBow, name: '황금 나무의 대궁' },
  [414]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatBow, name: '사자의 대궁' },

  [421]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '병사의 석궁' },
  [422]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '라이트 크로스보우' },
  [423]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '헤비 크로스보우' },
  [424]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '아바레스트' },
  [425]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '크레푸스의 흑건' },
  [426]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '도르래 석궁' },
  [427]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.crossBow, name: '월륜의 석궁' },

  [431]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.ballista, name: '핸디 발리스타' },
  [432]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.ballista, name: '대포 항아리' },

  [441]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.torch, name: '횃불' },
  [442]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.torch, name: '짐승 쫓는 횃불' },
  [443]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.torch, name: '강선 토치' },
  [444]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.torch, name: '보초의 횃불' },
  [445]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.torch, name: '영혼 불 토치' },
  [446]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.torch, name: '트리나의 등불' },

  [451]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '거의 망가진 나무 방패' },
  [452]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '쇠 압정 목제 방패' },
  [453]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '청백 목제 방패' },
  [454]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '성구의 목제 방패' },
  [455]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '붉은 가시 목제 방패' },
  [456]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '멍에 방패' },
  [457]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '버클러' },
  [458]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '철제 원형 방패' },
  [459]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '금장 철제 방패' },
  [460]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '뱀인간의 방패' },
  [461]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '얼음 문양 방패' },
  [462]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '갈라짐의 방패' },
  [463]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '조향사의 방패' },
  [464]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '죄인의 방패' },
  [465]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '뿔 회오리 방패' },
  [466]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '그을림의 방패' },
  [467]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.smallShield, name: '똬리 방패' },

  [471]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '매 문양 우드 실드' },
  [472]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '말 문양 우드 쉴드' },
  [473]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '촛불나무 우드 실드' },
  [474]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '화염 문양 우드 실드' },
  [475]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '침식된 목제 방패' },
  [476]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '태양 도읍의 방패' },
  [477]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '라운드 실드' },
  [478]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '라지 레더 실드' },
  [479]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '블랙 레더 실드' },
  [480]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '침식된 가죽 방패' },
  [481]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '히터 실드' },
  [482]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '푸른 문양 히터 실드' },
  [483]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '붉은 문양 히터 실드' },
  [484]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '짐승 문양 히터 실드' },
  [485]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '뒤집힌 매 히터 실드' },
  [486]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '일식 문양 히터 실드' },
  [487]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '카이트 실드' },
  [488]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '청금의 카이트 실드' },
  [489]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '전갈의 카이트 실드' },
  [490]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '쌍조의 카이트 실드' },
  [491]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '놋쇠 방패' },
  [492]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '땅 잃은 기사의 방패' },
  [493]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '백금의 방패' },
  [494]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '수인의 항아리 방패' },
  [495]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '카리아의 기사 방패' },
  [496]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '백은의 방패' },
  [497]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.mediumShield, name: '큰 거북의 등딱지' },

  [501]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '목제 대형 방패' },
  [502]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '군주군의 방패' },
  [503]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '철가시 대형 방패' },
  [504]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '압정 벽 방패' },
  [505]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '신성화의 방패' },
  [506]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '짐승 문양 황금 방패' },
  [507]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '성관의 타워 방패' },
  [508]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '교차수 타워 방패' },
  [509]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '뒤집힌 매 타워 방패' },
  [510]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '용의 타워 방패' },
  [511]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '명가의 대형 방패' },
  [512]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '금장 대형 방패' },
  [513]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '뻐꾸기 대형 방패' },
  [514]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '붉은 사자의 대형 방패' },
  [515]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '황금의 대형 방패' },
  [516]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '성수 문양 대형 방패' },
  [517]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '도가니의 뿔 방패' },
  [518]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '용 발톱의 방패' },
  [519]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '지문석의 방패' },
  [520]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '일식 문양 대형 방패' },
  [521]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '개미의 두갑' },
  [522]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '황금 나무의 대형 방패' },
  [523]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '해파리의 방패' },
  [524]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '안면 방패' },
  [525]: { mainCategory: Main.subWeapon, subCategory: SubWeapon.greatShield, name: '외눈 방패' },
}

const armorDb = {
  [531]: { mainCategory: Main.armor, subCategory: null, name: '방어구 정리 필요' },
}

const talismanDb = {
  [701]: { mainCategory: Main.talisman, subCategory: null, name: '붉은 호박 메달리온 ++' },
  [702]: { mainCategory: Main.talisman, subCategory: null, name: '붉은 종자의 탈리스만' },
  [703]: { mainCategory: Main.talisman, subCategory: null, name: '은혜의 물방울의 탈리스만' },
  [704]: { mainCategory: Main.talisman, subCategory: null, name: '푸른 호박 메달리온 ++' },
  [705]: { mainCategory: Main.talisman, subCategory: null, name: '푸른 종자의 탈리스만' },
  [706]: { mainCategory: Main.talisman, subCategory: null, name: '녹색 호박 메달리온 ++' },
  [707]: { mainCategory: Main.talisman, subCategory: null, name: '녹색 거북 탈리스만' },
  [708]: { mainCategory: Main.talisman, subCategory: null, name: '무구 덩어리 부적 +' },
  [709]: { mainCategory: Main.talisman, subCategory: null, name: '큰 항아리의 무구 덩어리' },
  [710]: { mainCategory: Main.talisman, subCategory: null, name: '황금 나무의 은총 ++' },
  [711]: { mainCategory: Main.talisman, subCategory: null, name: '라다곤의 각인' },
  [712]: { mainCategory: Main.talisman, subCategory: null, name: '라다곤의 문드러진 각인' },
  [713]: { mainCategory: Main.talisman, subCategory: null, name: '마리카의 각인' },
  [714]: { mainCategory: Main.talisman, subCategory: null, name: '마리카의 문드러진 각인' },
  [715]: { mainCategory: Main.talisman, subCategory: null, name: '별 부수기의 전승' },
  [716]: { mainCategory: Main.talisman, subCategory: null, name: '의수 검사의 전승' },
  [717]: { mainCategory: Main.talisman, subCategory: null, name: '별 보는 소녀의 전승' },
  [718]: { mainCategory: Main.talisman, subCategory: null, name: '두 손가락의 전승' },

  [721]: { mainCategory: Main.talisman, subCategory: null, name: '용 표식 방패의 탈리스만 ++' },
  [722]: { mainCategory: Main.talisman, subCategory: null, name: '용 표식 대형 방패의 탈리스만' },
  [723]: { mainCategory: Main.talisman, subCategory: null, name: '마력 용 표식의 탈리스만 ++' },
  [724]: { mainCategory: Main.talisman, subCategory: null, name: '염룡 표식의 탈리스만 ++' },
  [725]: { mainCategory: Main.talisman, subCategory: null, name: '뇌룡 표식의 탈리스만 ++' },
  [726]: { mainCategory: Main.talisman, subCategory: null, name: '성룡 표식의 탈리스만 ++' },
  [727]: { mainCategory: Main.talisman, subCategory: null, name: '진주룡 표식의 탈리스만 ++' },
  [728]: { mainCategory: Main.talisman, subCategory: null, name: '면역의 뿔 장식 +' },
  [729]: { mainCategory: Main.talisman, subCategory: null, name: '강건의 뿔 장식 +' },
  [730]: { mainCategory: Main.talisman, subCategory: null, name: '이성의 뿔 장식 +' },
  [731]: { mainCategory: Main.talisman, subCategory: null, name: '얼룩색 목걸이 +' },
  [732]: { mainCategory: Main.talisman, subCategory: null, name: '죽음의 왕자의 부스럼' },
  [733]: { mainCategory: Main.talisman, subCategory: null, name: '죽음의 왕자의 업창' },

  [741]: { mainCategory: Main.talisman, subCategory: null, name: '단검의 탈리스만' },
  [742]: { mainCategory: Main.talisman, subCategory: null, name: '곡검의 탈리스만' },
  [743]: { mainCategory: Main.talisman, subCategory: null, name: '쌍날검의 탈리스만' },
  [744]: { mainCategory: Main.talisman, subCategory: null, name: '도끼의 탈리스만' },
  [745]: { mainCategory: Main.talisman, subCategory: null, name: '망치의 탈리스만' },
  [746]: { mainCategory: Main.talisman, subCategory: null, name: '창의 탈리스만' },
  [747]: { mainCategory: Main.talisman, subCategory: null, name: '랜스의 탈리스만' },
  [748]: { mainCategory: Main.talisman, subCategory: null, name: '손톱의 탈리스만' },
  [749]: { mainCategory: Main.talisman, subCategory: null, name: '대형 방패의 탈리스만' },
  [750]: { mainCategory: Main.talisman, subCategory: null, name: '튼튼한 화살의 탈리스만' },
  [751]: { mainCategory: Main.talisman, subCategory: null, name: '먼 화살의 탈리스만' },

  [761]: { mainCategory: Main.talisman, subCategory: null, name: '마술사 구 탈리스만' },
  [762]: { mainCategory: Main.talisman, subCategory: null, name: '마술사 덩어리 탈리스만' },
  [763]: { mainCategory: Main.talisman, subCategory: null, name: '신도의 서포' },
  [764]: { mainCategory: Main.talisman, subCategory: null, name: '모인 신도의 서포' },
  [765]: { mainCategory: Main.talisman, subCategory: null, name: '원휘석 칼날' },
  [766]: { mainCategory: Main.talisman, subCategory: null, name: '녹스텔라의 달' },
  [767]: { mainCategory: Main.talisman, subCategory: null, name: '옛 왕의 탈리스만' },
  [768]: { mainCategory: Main.talisman, subCategory: null, name: '라다곤의 초상' },

  [771]: { mainCategory: Main.talisman, subCategory: null, name: '포효의 메달리온' },
  [772]: { mainCategory: Main.talisman, subCategory: null, name: '벗 항아리' },
  [773]: { mainCategory: Main.talisman, subCategory: null, name: '조향사의 탈리스만' },
  [774]: { mainCategory: Main.talisman, subCategory: null, name: '카리아의 휘장' },
  [775]: { mainCategory: Main.talisman, subCategory: null, name: '전사 항아리의 파편' },
  [776]: { mainCategory: Main.talisman, subCategory: null, name: '알렉산더의 파편' },
  [777]: { mainCategory: Main.talisman, subCategory: null, name: '고드프리의 초상' },

  [781]: { mainCategory: Main.talisman, subCategory: null, name: '큰 산양 탈리스만' },
  [782]: { mainCategory: Main.talisman, subCategory: null, name: '푸른 무희' },
  [783]: { mainCategory: Main.talisman, subCategory: null, name: '마력 전갈' },
  [784]: { mainCategory: Main.talisman, subCategory: null, name: '화염 전갈' },
  [785]: { mainCategory: Main.talisman, subCategory: null, name: '벼락 전갈' },
  [786]: { mainCategory: Main.talisman, subCategory: null, name: '신성한 전갈' },
  [787]: { mainCategory: Main.talisman, subCategory: null, name: '도가니 비늘의 탈리스만' },
  [788]: { mainCategory: Main.talisman, subCategory: null, name: '도가니 날개의 탈리스만' },
  [789]: { mainCategory: Main.talisman, subCategory: null, name: '도가니 혹의 탈리스만' },

  [791]: { mainCategory: Main.talisman, subCategory: null, name: '붉은 날개 칠지인' },
  [792]: { mainCategory: Main.talisman, subCategory: null, name: '푸른 날개 칠지인' },
  [793]: { mainCategory: Main.talisman, subCategory: null, name: '봉투검의 탈리스만' },
  [794]: { mainCategory: Main.talisman, subCategory: null, name: '봉투방패의 탈리스만' },
  [795]: { mainCategory: Main.talisman, subCategory: null, name: '붉은 흉악한 칼날' },
  [796]: { mainCategory: Main.talisman, subCategory: null, name: '푸른 흉악한 칼날' },
  [797]: { mainCategory: Main.talisman, subCategory: null, name: '유익검의 휘장' },
  [798]: { mainCategory: Main.talisman, subCategory: null, name: '부패 익검의 휘장' },
  [799]: { mainCategory: Main.talisman, subCategory: null, name: '밀리센트의 의수' },
  [800]: { mainCategory: Main.talisman, subCategory: null, name: '신의 살갗의 강보' },
  [801]: { mainCategory: Main.talisman, subCategory: null, name: '부패 권속의 환희' },
  [802]: { mainCategory: Main.talisman, subCategory: null, name: '피의 권속의 환희' },
  [803]: { mainCategory: Main.talisman, subCategory: null, name: '약탈의 카메오' },
  [804]: { mainCategory: Main.talisman, subCategory: null, name: '선조령의 뿔' },
  [805]: { mainCategory: Main.talisman, subCategory: null, name: '금 스카라베' },
  [806]: { mainCategory: Main.talisman, subCategory: null, name: '은 스카라베' },

  [811]: { mainCategory: Main.talisman, subCategory: null, name: '크레푸스의 작은 병' },
  [812]: { mainCategory: Main.talisman, subCategory: null, name: '몸 가리는 베일' },
  [813]: { mainCategory: Main.talisman, subCategory: null, name: '긴 꼬리 고양이 탈리스만' },
  [814]: { mainCategory: Main.talisman, subCategory: null, name: '갈고리 손가락의 위장 거울' },
  [815]: { mainCategory: Main.talisman, subCategory: null, name: '주인의 위장 거울' },
  [816]: { mainCategory: Main.talisman, subCategory: null, name: '샤브리리의 화' },
  [817]: { mainCategory: Main.talisman, subCategory: null, name: '디디카의 화' },
  [818]: { mainCategory: Main.talisman, subCategory: null, name: '희생의 가는 가지' },
}

const skillDb = {
  [821]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '파고들어 올려 베기' },
  [822]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '파고들어 회전 베기' },
  [823]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '난격' },
  [824]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '사자 베기' },
  [825]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '암석검' },
  [826]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '킥' },
  [827]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '참기' },
  [828]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '드롭 어택' },
  [829]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '땅 흔들기' },
  [830]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '호라 루의 땅 흔들기' },
  [831]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '워 크라이' },
  [832]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '야만적인 포효' },
  [833]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '과시하는 포효' },
  [834]: { mainCategory: Main.skill, subCategory: Skill.heavy, name: '트롤의 포효' },

  [841]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '회전 베기' },
  [842]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '관통 찌르기' },
  [843]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '엄니 찌르기' },
  [844]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '연속 찌르기' },
  [845]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '2연속 베기' },
  [846]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '검무' },
  [847]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '거합' },
  [848]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '퀵스텝' },
  [849]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '사냥개의 스텝' },
  [850]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '안개의 맹금' },
  [851]: { mainCategory: Main.skill, subCategory: Skill.keen, name: '짐승의 포효' },

  [861]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '준비 자세' },
  [862]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '돌격' },
  [863]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '회전격' },
  [864]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '거인 사냥' },
  [865]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '폭풍의 칼날' },
  [866]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '폭풍의 습격' },
  [867]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '폭풍 부르기' },
  [868]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '남각' },
  [869]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '진공 베기' },
  [870]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '협공하는 환영' },
  [871]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '디터미네이션' },
  [872]: { mainCategory: Main.skill, subCategory: Skill.quality, name: '도읍 기사의 결의' },

  [881]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '휘석 돌팔매' },
  [882]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '휘검의 원진' },
  [883]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '카리아의 대검' },
  [884]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '그레이트 카리아' },
  [885]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '돌아라 돌아라' },
  [886]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '로레타의 참격' },
  [887]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '그라비타스' },
  [888]: { mainCategory: Main.skill, subCategory: Skill.magic, name: '암흑파' },

  [891]: { mainCategory: Main.skill, subCategory: Skill.fire, name: '염격' },
  [892]: { mainCategory: Main.skill, subCategory: Skill.fire, name: '적사자의 화염' },
  [893]: { mainCategory: Main.skill, subCategory: Skill.fire, name: '용암 분화' },

  [901]: { mainCategory: Main.skill, subCategory: Skill.flameArt, name: '주교의 돌진' },
  [902]: { mainCategory: Main.skill, subCategory: Skill.flameArt, name: '흑염의 회오리' },

  [911]: { mainCategory: Main.skill, subCategory: Skill.lightning, name: '낙뢰' },
  [912]: { mainCategory: Main.skill, subCategory: Skill.lightning, name: '뇌격참' },
  [913]: { mainCategory: Main.skill, subCategory: Skill.lightning, name: '벼락 양' },

  [921]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '신성한 칼날' },
  [922]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '기도의 일격' },
  [923]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '성스러운 빛고리' },
  [924]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '성률' },
  [925]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '성률 공유' },
  [926]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '황금의 땅' },
  [927]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '황금의 드롭 어택' },
  [928]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '황금 나무에 맹세코' },
  [929]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '무적' },
  [930]: { mainCategory: Main.skill, subCategory: Skill.sacred, name: '성역' },

  [931]: { mainCategory: Main.skill, subCategory: Skill.poison, name: '독 안개' },
  [932]: { mainCategory: Main.skill, subCategory: Skill.poison, name: '독나방은 두 번 춤춘다' },

  [941]: { mainCategory: Main.skill, subCategory: Skill.blood, name: '피의 칼날' },
  [942]: { mainCategory: Main.skill, subCategory: Skill.blood, name: '피의 참격' },
  [943]: { mainCategory: Main.skill, subCategory: Skill.blood, name: '피의 징수' },
  [944]: { mainCategory: Main.skill, subCategory: Skill.blood, name: '할복' },

  [951]: { mainCategory: Main.skill, subCategory: Skill.cold, name: '얼음창' },
  [952]: { mainCategory: Main.skill, subCategory: Skill.cold, name: '냉기 안개' },
  [953]: { mainCategory: Main.skill, subCategory: Skill.cold, name: '서리 밟기' },

  [961]: { mainCategory: Main.skill, subCategory: Skill.occult, name: '환영창' },
  [962]: { mainCategory: Main.skill, subCategory: Skill.occult, name: '명탈권' },
  [963]: { mainCategory: Main.skill, subCategory: Skill.occult, name: '흰 그림자의 유인' },
  [964]: { mainCategory: Main.skill, subCategory: Skill.occult, name: '암살의 작법' },

  [971]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '강화 사격' },
  [972]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '관통 사격' },
  [973]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '연속 사격' },
  [974]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '허공에 쏘기' },
  [975]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '추적 사격' },
  [976]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '애로우 레인' },

  [981]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '패리' },
  [982]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '황금 패리' },
  [983]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '폭풍의 벽' },
  [984]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '방패 강타' },
  [985]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '돌격 강타' },
  [986]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '철벽의 방패' },
  [987]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '토푸스의 역장' },
  [988]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '카리아의 앙갚음' },
  [989]: { mainCategory: Main.skill, subCategory: Skill.etc, name: '전투 기술 없음' },
}

const spellDb = {
  [991]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석 돌팔매' },
  [992]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석 빠른 돌팔매' },
  [993]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석 큰 돌팔매' },
  [994]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석의 혜성' },
  [995]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '별똥별' },
  [996]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '소용돌이 돌팔매' },
  [997]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석의 유성' },
  [998]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '유성군' },
  [999]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석의 아크' },
  [1000]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '결정 연탄' },
  [1001]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '결정 산탄' },
  [1002]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '하이마의 포탄' },
  [1003]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '하이마의 대형 망치' },
  [1004]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '암반 부수기' },
  [1005]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '암반 발파' },
  [1006]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '마력의 무기' },
  [1007]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '마력의 방패' },
  [1008]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '별 등불' },
  [1009]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '마술의 땅' },
  [1010]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '토푸스의 역장' },
  [1011]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '혜성 아줄' },
  [1012]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '멸망의 유성' },
  [1013]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '창성의 비' },

  [1021]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '마술의 휘검' },
  [1022]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘검의 원진' },
  [1023]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '카리아의 원진' },
  [1024]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '거검진' },
  [1025]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '쏟아지는 마력' },
  [1026]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '로레타의 대궁' },
  [1027]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '로레타의 묘기' },
  [1028]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '레날라의 만월' },
  [1029]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '라니의 만월' },
  [1030]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '카리아의 속검' },
  [1031]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '카리아의 대검' },
  [1032]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '카리아의 찌르기' },
  [1033]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '아듀라의 달의 검' },
  [1034]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '냉정' },
  [1035]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '카리아의 응보' },

  [1041]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '기적의 돌팔매' },
  [1042]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '밤의 돌팔매' },
  [1043]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '밤의 혜성' },
  [1044]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '밤 무녀의 안개' },
  [1045]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '보이지 않는 칼날' },
  [1046]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '보이지 않는 모습' },
  [1047]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '영원한 암흑' },

  [1051]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '용암탄' },
  [1052]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '솟구치는 용암' },
  [1053]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '겔미어의 분노' },
  [1054]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '라이커드의 원혼' },

  [1061]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '휘석의 얼음덩어리' },
  [1062]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '얼음의 안개' },
  [1063]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '빙결의 무기' },
  [1064]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '자미엘의 얼음 폭풍' },

  [1071]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '부서지는 결정' },
  [1072]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '쏘아지는 결정' },
  [1073]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '결정 해방' },

  [1081]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '중력탄' },
  [1082]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '별 부수기' },
  [1083]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '암석탄' },
  [1084]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '메테오라이트' },
  [1085]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '아스테르 메테오' },

  [1091]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '신탁의 비눗방울' },
  [1092]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '신탁의 큰 비눗방울' },

  [1101]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '죄의 가시' },
  [1102]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '벌의 가시' },

  [1111]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '원혼 부르기' },
  [1112]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '옛 죽음의 영혼' },
  [1113]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '폭발하는 영혼 화염' },
  [1114]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '피아의 안개' },
  [1115]: { mainCategory: Main.spell, subCategory: Spell.magic, name: '티비아의 부름' },

  [1121]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '성급한 회복' },
  [1122]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '회복' },
  [1123]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '대 회복' },
  [1124]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '왕의 회복' },
  [1125]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '독의 치유' },
  [1126]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '왕의 치유' },
  [1127]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '마력 방호' },
  [1128]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '화염 방호' },
  [1129]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '벼락 방호' },
  [1130]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '신성 방호' },
  [1131]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '왕의 신성 방호' },
  [1132]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '거절' },
  [1133]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '그림자 보내기' },
  [1134]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '어둠' },
  [1135]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '암부의 보법' },

  [1141]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금 나무에 맹세코' },
  [1142]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금의 마력 방호' },
  [1143]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금의 벼락 방호' },
  [1144]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금 나무의 수호' },
  [1145]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금의 분노' },

  [1151]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금 나무의 회복' },
  [1152]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '은혜의 축복' },
  [1153]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '황금 나무의 은혜' },
  [1154]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '도가니의 모습/후대' },
  [1155]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '도가니의 모습/꼬리' },
  [1156]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '도가니의 모습/뿔' },
  [1157]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '엘데의 유성' },
  [1158]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '흑검' },

  [1161]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '빛고리' },
  [1162]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '세 개의 빛고리' },
  [1163]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '라다곤의 빛고리' },
  [1164]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '죽음을 바로잡는 성률' },
  [1165]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '성률의 치료' },
  [1166]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '성률의 검' },
  [1167]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불역의 방패' },
  [1168]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '인과성 원리' },
  [1169]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '회귀성 원리' },

  [1171]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '벼락 창' },
  [1172]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '뇌격' },
  [1173]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '조준하는 뇌격' },
  [1174]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '고룡의 뇌창' },
  [1175]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '고룡의 뇌격' },
  [1176]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '란삭스의 치도' },
  [1177]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '포르삭스의 뇌창' },
  [1178]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '얼음 뇌창' },
  [1179]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '죽음의 뇌격' },
  [1180]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '벼락의 무기' },
  [1181]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '용뢰의 가호' },
  [1182]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '바이크의 용뢰' },

  [1191]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불 붙이기' },
  [1192]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불이여!' },
  [1193]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불 던지기' },
  [1194]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '거인의 불을 받으라' },
  [1195]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불이여 쏟아져라' },
  [1196]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '악신의 불' },
  [1197]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불이여 솟구쳐라' },
  [1198]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불이여 회오리쳐라' },
  [1199]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '모두 불태워라!' },
  [1200]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불의 치유여' },
  [1201]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불의 수호여' },
  [1202]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불이여, 힘을!' },
  [1203]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '불의 대죄' },

  [1211]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '흑염' },
  [1212]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '쓸어버리는 흑염' },
  [1213]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '흑염의 의식' },
  [1214]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '흑염의 칼날' },
  [1215]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '흑염의 수호' },
  [1216]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '귀족의 배짱' },

  [1221]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '짐승 발톱' },
  [1222]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '그랭의 짐승 발톱' },
  [1223]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '짐승의 돌' },
  [1224]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '짐승의 바위' },
  [1225]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '짐승의 강건' },
  [1226]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '짐승의 생명' },

  [1231]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '파리떼' },
  [1232]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '혈염의 발톱자국' },
  [1233]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '피의 수여' },
  [1234]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '혈염의 칼날' },

  [1241]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '독 안개' },
  [1242]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '독 칼날' },
  [1243]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '곤충 실' },
  [1244]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '붉은 에오니아' },

  [1251]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '미친 불' },
  [1252]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '참을 수 없는 미친 불' },
  [1253]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '공열광화' },
  [1254]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '샤브리리의 외침' },
  [1255]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '발광전염' },

  [1261]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '용염' },
  [1262]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '아길의 화염' },
  [1263]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '용암 브레스' },
  [1264]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '테오드릭스의 용암' },
  [1265]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '휘석 브레스' },
  [1266]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '스마라그의 휘석' },
  [1267]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '부패 브레스' },
  [1268]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '엑디키스의 부패' },
  [1269]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '용빙' },
  [1270]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '볼레아리스의 얼음 안개' },
  [1271]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '플라키두삭스의 멸망' },
  [1272]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '용 발톱' },
  [1273]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '용 물기' },
  [1274]: { mainCategory: Main.spell, subCategory: Spell.incantation, name: '그레이오르의 포효' },
}

const spiritDb = {
  [1281]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '헤매는 귀인의 뼛가루' },
  [1282]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '귀인 마술사의 뼛가루' },
  [1283]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '방랑 민족의 뼛가루' },
  [1284]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '부패한 망자의 뼛가루' },
  [1285]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '민병 스켈레톤의 뼛가루' },
  [1286]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '산적 스켈레톤의 뼛가루' },
  [1287]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '백금의 사람의 뼛가루' },
  [1288]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '날개 혼종의 뼛가루' },
  [1289]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '아인단의 뼛가루' },
  [1290]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '진흙인간의 뼛가루' },
  [1291]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '신탁의 사자들의 뼛가루' },
  [1292]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '낙오된 늑대의 뼛가루' },
  [1293]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '썩은 들개의 뼛가루' },
  [1294]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '큰쥐의 뼛가루' },
  [1295]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '전쟁매의 뼛가루' },
  [1296]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '육지멍게의 뼛가루' },
  [1297]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '영해파리의 뼛가루' },
  [1298]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '작은 미란다의 뼛가루' },
  [1299]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '아귀 임프의 뼛가루' },
  [1300]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '특공대의 뼛가루' },

  [1301]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '궁병의 뼛가루' },
  [1302]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '대형 방패병의 뼛가루' },
  [1303]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '시종의 뼛가루' },
  [1304]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '천한 병사의 뼛가루' },
  [1305]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '인형 병사의 뼛가루' },
  [1306]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '새 인형 병사의 뼛가루' },
  [1307]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '카이덴 용병의 뼛가루' },
  [1308]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '호박 광병의 뼛가루' },
  [1309]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '불의 승병의 뼛가루' },
  [1310]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '선조령의 백성의 뼛가루' },
  [1311]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '아즈라 수인의 뼛가루' },
  [1312]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '뱀인간의 뼛가루' },
  [1313]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '결정인의 뼛가루' },
  [1314]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '부패의 권속의 뼛가루' },
  [1315]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '휘석 마술사의 뼛가루' },
  [1316]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '쌍현 마술사의 뼛가루' },
  [1317]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '고드릭 병사의 뼛가루' },
  [1318]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '레아 루카리아 병사의 뼛가루' },
  [1319]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '로데일 병사의 뼛가루' },
  [1320]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '라단 병사의 뼛가루' },
  [1321]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '성수 병사의 뼛가루' },
  [1322]: { mainCategory: Main.spiritAshes, subCategory: Spirit.default, name: '영묘 병사의 뼛가루' },

  [1331]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '폭풍 매 디네' },
  [1332]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '땅 잃은 기사 오레그' },
  [1333]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '땅 잃은 기사 잉바르' },
  [1334]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '사냥개기사 플로' },
  [1335]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '전쟁마술사 유그' },
  [1336]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '백금의 라티나' },
  [1337]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '조향사 트리샤' },
  [1338]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '타락조향사 카르만' },
  [1339]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '흉조잡이 로로' },
  [1340]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '흑염 승병 아몬' },
  [1341]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '고룡 기사 크리스토프' },
  [1342]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '적사자기사 오우가' },
  [1343]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '목 없는 기사 루텔' },
  [1344]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '귀부기사 핀레이' },
  [1345]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '검은 칼날 티시' },
  [1346]: { mainCategory: Main.spiritAshes, subCategory: Spirit.special, name: '화신의 물방울의 뼛가루' },

  [1351]: { mainCategory: Main.spiritAshes, subCategory: Spirit.marionette, name: '손가락 무녀 사로리나의 꼭두각시' },
  [1352]: { mainCategory: Main.spiritAshes, subCategory: Spirit.marionette, name: '항아리 남자의 꼭두각시' },
  [1353]: { mainCategory: Main.spiritAshes, subCategory: Spirit.marionette, name: '잠의 화살 돌로레스의 꼭두각시' },
  [1354]: { mainCategory: Main.spiritAshes, subCategory: Spirit.marionette, name: '네펠리 루의 꼭두각시' },
  [1355]: { mainCategory: Main.spiritAshes, subCategory: Spirit.marionette, name: '대변 먹는 자의 꼭두각시' },
  [1356]: { mainCategory: Main.spiritAshes, subCategory: Spirit.marionette, name: '밤 무녀와 검사 꼭두각시' },
}

const gestureDb = {
  [1361]: { mainCategory: Main.gesture, subCategory: null, name: '제스처 정리 필요' },
}

const npcDb = {
  [1401]: { mainCategory: Main.npc, subCategory: Npc.default, name: '보크' },
  [1402]: { mainCategory: Main.npc, subCategory: Npc.default, name: '알렉산더' },
  [1403]: { mainCategory: Main.npc, subCategory: Npc.default, name: '유라' },
  [1404]: { mainCategory: Main.npc, subCategory: Npc.default, name: 'NPC 추가 정리 필요' },
}

const generalItemDb = {
  [2001]: { mainCategory: Main.generalItem, subCategory: Item.core, name: '영약의 성배병' },
}

// enum SubCategoryIngGeneralItem {
//   core, // 영약의 성배병, 도구 가방, 숫돌 소도, 영마의 손가락 피리, 환혼의 종, 부적주머니
//   event, // 이벤트 - 퀘스트 관련
//   weaponUpgrade, // 단석
//   spiritUpgrade, // 은방울꽃
//   bellBearing, // 방울
//   assistant, // 보조 - 랜턴, 망원경
//   cristalTears, // 성배병 물방울
//   consumables, // 소모품
//   bowl, // 그릇 - 항아리, 조향병
//   throw, // 투척물
//   enchant, // 인챈트
//   multiPlay, // 멀티용
//   rune, // 룬
//   greatRune, // 거대한 룬
//   remembrances, // 추억
//   ending, // 수복 룬
//   material, // 재료
//   recipe, // 제작서
// }

const itemDb = {
  ...weaponDb,
  ...subWeaponDb,
  ...armorDb,
  ...talismanDb,
  ...skillDb,
  ...spellDb,
  ...spiritDb,
  ...gestureDb,
  ...npcDb,
  ...generalItemDb,
}

export default itemDb;